site/Site/Controllers/StatusController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DataInterfaces.Repositories;
using Data;
using Site.Models;
using Site.Services;
using log4net;

namespace Site.Controllers
{
    public class StatusController : Controller
    {
        private HttpRequestBase _requestBase;
        private IStatusService _statusService;
        private HttpSessionStateBase _session;
        private ILog _log;
        public const int ItemsPerPage = 10;

        public StatusController(IStatusService statusService, HttpSessionStateBase session, HttpRequestBase requestBase, ILog log)
        {
            _statusService = statusService;
            _session = session;
            _requestBase = requestBase;
            _log = log;
        }

        [Authorize]
        public ActionResult Index(int? page)
        {
            if (!page.HasValue)
                page = 1;

            var statusList = _statusService.GetHistory((int)_session["UserId"], page.Value, ItemsPerPage);

            return View("History", statusList);
        }

        [Authorize]
        public ActionResult New(string message)
        {
            if (string.IsNullOrWhiteSpace(message))
                return View("New");

            var statusId = _statusService.Add(message, (int)_session["UserId"]);

            return RedirectToAction("Single", new { statusId = statusId });
        }

        [Authorize]
        public ActionResult Single(int statusId)
        {
            var viewUser = new ViewUser { UserId = (int)_session["UserId"], IpAddress = _requestBase.UserHostAddress };
            return View("Single", _statusService.Get(statusId, viewUser));
        }

        [Authorize]
        public ActionResult Search(string searchText, int? page)
        {
            if (!page.HasValue)
                page = 1;

            var statusList = _statusService.Search(searchText, page.Value, ItemsPerPage);

            return View("Search", statusList);
        }

        [Authorize]
        public ActionResult AddLike(int statusId)
        {
            _statusService.AddLike(statusId, _requestBase.UserHostAddress, (int)_session["UserId"]);
            return RedirectToAction("Single", new { statusId = statusId });
        }
    }
}

site/Site/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Site.Models;
using SiteLogic;
using Site.Services;
using System.Web.Security;
using log4net;

namespace Site.Controllers
{
    public class UserController : Controller
    {
        private readonly IAuthenticationService _authenticationService;
        private readonly HttpSessionStateBase _session;
        private readonly ILog _log;

        public UserController(IAuthenticationService authenticationService, HttpSessionStateBase session, ILog log)
        {
            _authenticationService = authenticationService;
            _session = session;
            _log = log;
        }

        public ActionResult Index()
        {
            return View(new AuthenticationDetails());
        }

        [HttpPost]
        public ActionResult Index(AuthenticationDetails auth)
        {
            if (ModelState.IsValid)
            {
                var user = _authenticationService.AutheticateUser(HttpContext, auth.Login, auth.Password);
                if (user != null)
                {
                    FormsAuthentication.SetAuthCookie(auth.Login, false);
                    _session["UserId"] = user.UserId;
                    _log.Info(string.Format("login suceeded, login: \"{0}\"", auth.Login));
                    return RedirectToAction("index", "");
                }

                auth.LoginFailed = true;
                _log.Info(string.Format("login failed, login: \"{0}\"", auth.Login));

                return View(auth);
            }
            _log.Info("Failed login attempt, model invalid");

            return View(auth);
        }

        [HttpGet]
        public ActionResult Logout(AuthenticationDetails auth)
        {
            _session.Abandon();
            return RedirectToAction("index", "");
        }
    }
}

site/Site/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <title>@ViewBag.Title</title>
        <link href="~/favicon.ico" rel="shortcut icon" type="image/x-icon" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link href="/Shared/bootstrap.min.css" rel="stylesheet">
        <link href="/Shared/site.css" rel="stylesheet">
        <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
        <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
        <!--[if lt IE 9]>
          <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
          <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
        <![endif]-->
    </head>
    <body>
        <header>
            <div class="content-wrapper">
                <div class="collapse navbar-collapse">
                    <nav class="navbar navbar-default" role="navigation">
                        <ul id="menu" class="nav navbar-nav navbar-right">
                            <li>@Html.ActionLink("Home", "Index", "Home")</li>
                            @if (!@ViewBag.IsLoggedIn)
                            {
                                <li>@Html.ActionLink("Login", "Index", "User")</li>
                            }
                            @if (@ViewBag.IsLoggedIn)
                            {
                                <li>@Html.ActionLink("Logout", "Logout", "User")</li>
                                <li>@Html.ActionLink("History", "", "Status")</li>
                                <li>@Html.ActionLink("New Post", "New", "Status")</li>
                                <li class="searchFixes">
                                    <form class="navbar-form navbar-right" role="search" action="/Status/Search" method="get">
                                        <div class="form-group">
                                            @Html.TextBox("searchText", "", new { placeholder = "Search", Class = "form-control" })
                                        </div>
                                    </form>
                                </li>
                            }
                        </ul>
                    </nav>
                </div>
            </div>
        </header>
        <div id="body">
            @RenderSection("featured", required: false)
            <section class="content-wrapper main-content clear-fix">
                @RenderBody()
            </section>
        </div>

        @RenderSection("scripts", required: false)
    </body>
</html>